In [1]:
import numpy as np

In [41]:
numara = np.arange(11)
numara

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
np.random.shuffle(numara)
numara

array([ 8, 10,  6,  3,  7,  2,  4,  0,  9,  5,  1])

In [53]:
degistir = np.random.randint(1,11,2)
degistir

array([ 1, 10])

In [55]:
degistir[1]

10

In [127]:
numara

array([ 8, 10,  6,  3,  7,  2,  4,  0,  9,  5,  1])

In [128]:
degistir

array([ 1, 10])

In [ ]:
numara[]

In [67]:
def yerDegistir(dizi1, dizi2):
    for i in range(len(dizi2)):
        for j in range(len(dizi1)):
            if dizi2[i] == dizi1[j]:
                temp = dizi1[j]
                dizi1[j] = dizi2[i]
                dizi2[i] = temp
    return dizi1    

In [68]:
yerDegistir(numara,degistir)
print(numara)
print(degistir)

[ 8 10  6  3  7  2  4  0  9  5  1]
[ 1 10]


In [17]:
maliyet = np.array([np.random.randint(1,50,10) for i in range(10)])

In [18]:
maliyet

array([[12, 29, 34, 21, 33, 25, 45,  6,  5,  8],
       [25, 25, 45, 35, 41, 16, 14, 25, 16,  7],
       [22, 43, 23, 12, 49, 13, 29, 33, 16, 45],
       [41, 43, 46, 44, 34, 46, 41, 26, 10, 38],
       [ 1, 19, 24,  4, 30, 17, 21, 19, 49, 15],
       [16, 18, 26, 47, 49, 43, 18, 33, 18, 42],
       [17, 42, 27, 13, 31, 18, 18, 17,  1, 32],
       [38, 10,  1, 39, 23, 33,  3,  4, 32, 36],
       [28, 19, 14, 44, 49, 30, 46, 12, 23, 38],
       [12, 22, 34, 32, 44, 25, 33, 38, 10, 41]])

In [19]:
maliyet[0].sum()

218

In [20]:
tabuSuresi = 3
maxIter = 10
degistir = np.random.randint(1,10,2)
degistir

array([6, 8])

In [21]:
toplamlar = []
for i in range(10):
    toplamlar.append(maliyet[i].sum())
toplamlar

[218, 249, 285, 369, 199, 310, 216, 219, 303, 291]

In [ ]:
def tabu():
    for i in maxIter:
        siralama = np.random.ranint(1,10,10)
        enIyiCozum = siralama[i].sum()

In [60]:
for i in range(maxIter):
    siralama = np.random.randint(1,10,10)
    for j in siralama:
        maliyet[siralama[i][j]] 
    
    print(i , siralama, matris[i].sum())

    enIyiCozum = matris[i].sum()
enIyiCozum

0 [6 8 1 9 7 7 1 9 1 8] 56
1 [5 7 6 5 1 7 8 9 7 7] 42
2 [7 2 4 5 3 2 6 5 1 6] 65
3 [6 4 9 3 1 9 4 5 4 9] 45
4 [6 7 3 7 7 1 7 2 1 8] 37
5 [9 4 7 5 8 8 2 3 4 4] 38
6 [3 2 2 7 7 5 9 6 3 5] 37
7 [9 9 8 5 4 7 6 1 4 2] 53
8 [9 4 4 4 9 6 3 5 3 2] 49
9 [1 4 7 5 4 6 1 8 4 9] 63


63

In [125]:
a = [1,2,3,4]
b = [2,4]

In [123]:
a.index(b[1])

3

In [126]:
for i in range(len(a)):
    if a[i] == b[0]:
        temp1 = a[i]
        a[i] = b[1]
        if a[i] == b[1]:
            temp2 = a[i]
            a[i] = b[0]
print(a)


[1, 2, 3, 4]


In [144]:
np.array([[0,3.6,5.1,10,15,20,16,14,23,26],[3.6,0,3.6,6.4,12,18,13,11,20,23],[5.1,3.6,0,7.1,11,15,16,11,18,22],
          [10,6.4,7.1,0,7,16,10,4.2,14,17], [15,12,11,7,0,9.9,15,5,7.8,11],[20,18,15,16,9.9,0,25,15,12,15],
         [16,13,16,10,15,25,0,10,19,21],[14,11,11,4.2,5,15,10,0,10,13],[23,20,18,14,7.8,12,19,10,0,3.6],
         [26,23,22,17,11,15,21,13,3.6,0]])

array([[ 0. ,  3.6,  5.1, 10. , 15. , 20. , 16. , 14. , 23. , 26. ],
       [ 3.6,  0. ,  3.6,  6.4, 12. , 18. , 13. , 11. , 20. , 23. ],
       [ 5.1,  3.6,  0. ,  7.1, 11. , 15. , 16. , 11. , 18. , 22. ],
       [10. ,  6.4,  7.1,  0. ,  7. , 16. , 10. ,  4.2, 14. , 17. ],
       [15. , 12. , 11. ,  7. ,  0. ,  9.9, 15. ,  5. ,  7.8, 11. ],
       [20. , 18. , 15. , 16. ,  9.9,  0. , 25. , 15. , 12. , 15. ],
       [16. , 13. , 16. , 10. , 15. , 25. ,  0. , 10. , 19. , 21. ],
       [14. , 11. , 11. ,  4.2,  5. , 15. , 10. ,  0. , 10. , 13. ],
       [13. , 20. , 18. , 14. ,  7.8, 12. , 19. , 10. ,  0. ,  3.6],
       [26. , 23. , 22. , 17. , 11. , 15. , 21. , 13. ,  3.6,  0. ]])

In [150]:
import numpy as np
import heapq
import time

In [162]:
cities = [
    [0, 3.6, 5.1, 10, 15, 20, 16, 14, 23, 26],
    [3.6, 0, 3.6, 6.4, 12, 18, 13, 11, 20, 23],
    [5.1, 3.6, 0, 7.1, 11, 15, 16, 11, 18, 22],
    [10, 6.4, 7.1, 0, 7, 16, 10, 4.2, 14, 17],
    [15, 12, 11, 7, 0, 9.9, 15, 5, 7.8, 11],
    [20, 18, 15, 16, 9.9, 0, 25, 15, 12, 15],
    [16, 13, 16, 10, 15, 25, 0, 10, 19, 21],
    [14, 11, 11, 4.2, 5, 15, 10, 0, 10, 13],
    [23, 20, 18, 14, 7.8, 12, 19, 10, 0, 3.6],
    [26, 23, 22, 17, 11, 15, 21, 13, 3.6, 0]
]

In [227]:
def fitness(cozum):
    s = 0
    cd = list(cozum).copy()
    for i in range(len(cozum) - 1):
        s += cities[cd[i]][cd[i+1]]
    return s
# maliyeti hesaplıyor

In [164]:
def get_neighbors(cozum):
    neighbors = []
    cozum = list(cozum)
    for i in range(len(cozum) - 1):
        cnew = cozum.copy()
        cnew[i], cnew[i+1] = cnew[i+1], cnew[i]
        neighbors.append(cnew)
    return neighbors
# gelen cozumeden komsuluk matrisi olusturuyor

In [165]:
def rassal_cozum_uret():
    bazCozum = list(range(10))
    ornekCozum = bazCozum.copy()
    np.random.shuffle(ornekCozum)
    ornekCozum = list(ornekCozum)
    return ornekCozum

In [185]:
rassal_cozum_uret()

[1, 7, 6, 4, 8, 3, 2, 9, 5, 0]

In [222]:
get_neighbors([1, 7, 6, 4, 8, 3, 2, 9, 5, 0])

[[7, 1, 6, 4, 8, 3, 2, 9, 5, 0],
 [1, 6, 7, 4, 8, 3, 2, 9, 5, 0],
 [1, 7, 4, 6, 8, 3, 2, 9, 5, 0],
 [1, 7, 6, 8, 4, 3, 2, 9, 5, 0],
 [1, 7, 6, 4, 3, 8, 2, 9, 5, 0],
 [1, 7, 6, 4, 8, 2, 3, 9, 5, 0],
 [1, 7, 6, 4, 8, 3, 9, 2, 5, 0],
 [1, 7, 6, 4, 8, 3, 2, 5, 9, 0],
 [1, 7, 6, 4, 8, 3, 2, 9, 0, 5]]

In [231]:
bazCozum = list(range(10))
ornekCozum = bazCozum.copy()
np.random.shuffle(ornekCozum)
ornekCozum = list(ornekCozum)

sBest = ornekCozum.copy()
bestCandidate = ornekCozum.copy()
tabuList = []
maxtabu = 200
s0 = sBest
heapq.heappush(tabuList, (time.time(), s0))
cost = float('inf')
control = True
PATIENCE = 1000
sabir = 0

while True:
    if not control:
        bestCandidate = rassal_cozum_uret()
    
    sNeihborhood = get_neighbors(bestCandidate)
    bestCandidate = sNeihborhood[0]
    
    control = False
    for sCandidate in sNeihborhood:
        if not (sCandidate in [i[1] for i in tabuList]) and (fitness(sCandidate) < fitness(bestCandidate)):
            control = True
            bestCandidate = sCandidate
            
            
    if fitness(bestCandidate) < fitness(sBest):
        sBest = bestCandidate
        cost = fitness(sBest)
        print(cost ,sBest)
        #print(get_neighbors(bestCandidate))
        sabir = 0
    else:
        sabir += 1
        
    if sabir >= PATIENCE:
        break
        
    heapq.heappush(tabuList, (time.time(), bestCandidate))
    if len(tabuList) > maxtabu:
        heapq.heappop(tabuList)

128.5 [7, 8, 6, 5, 4, 1, 0, 3, 9, 2]
115.5 [7, 6, 8, 5, 4, 1, 0, 3, 9, 2]
105.6 [7, 6, 8, 5, 4, 1, 0, 3, 2, 9]
95.69999999999999 [7, 6, 8, 5, 4, 1, 0, 2, 3, 9]
86.7 [6, 7, 8, 5, 4, 1, 0, 2, 3, 9]
84.19999999999999 [1, 0, 7, 9, 8, 5, 4, 2, 3, 6]
81.19999999999999 [0, 1, 7, 9, 8, 5, 4, 2, 3, 6]
81.0 [9, 4, 6, 1, 0, 2, 3, 7, 8, 5]
78.29999999999998 [7, 4, 5, 9, 8, 6, 3, 2, 0, 1]
76.79999999999998 [7, 4, 5, 9, 8, 6, 3, 2, 1, 0]
75.79999999999998 [7, 4, 5, 8, 9, 6, 3, 2, 1, 0]
75.3 [5, 9, 8, 4, 6, 3, 7, 1, 0, 2]
70.7 [5, 9, 8, 4, 6, 7, 3, 1, 0, 2]
66.5 [5, 9, 8, 4, 7, 6, 3, 1, 0, 2]
65.7 [5, 9, 8, 4, 7, 6, 3, 2, 1, 0]


In [187]:
fitness([9    , 2   ,  1   ,  3     ,4  ,   5   ,  7  ,   8   ,  6    , 0])

108.9